# Configuracion de ejemplo para sync_ad_maximo
# No guardar secretos reales en este archivo.

app.name=sync-ad-maximo
app.timezone=America/Guayaquil
app.locale=es-EC

config.external.path=

sync.strategy.cedula9Digitos=AGREGAR_CERO
sync.web.allowedUser=maxadmin

ad.enabledFilterBase=
ad.disabledFilterBase=
maximo.personSchema=MAXIMO
maximo.emailSchema=MAXIMO
