-- Tabla de ejecuciones de sincronización
CREATE TABLE MAXIMO.SYNC_AD_MAXIMO_RUN (
  RUN_ID NUMBER PRIMARY KEY,
  FECHA_INICIO TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  FECHA_FIN TIMESTAMP(6),
  MODO VARCHAR2(20) NOT NULL,
  PROCESO VARCHAR2(50) NOT NULL,
  USUARIO_EJECUTOR VARCHAR2(100),
  ORIGEN_EJECUCION VARCHAR2(30),
  ESTADO VARCHAR2(50) NOT NULL,
  TOTAL_MAXIMO NUMBER DEFAULT 0 NOT NULL,
  TOTAL_AD NUMBER DEFAULT 0 NOT NULL,
  TOTAL_MIGRADOS NUMBER DEFAULT 0 NOT NULL,
  TOTAL_CREADOS NUMBER DEFAULT 0 NOT NULL,
  TOTAL_INACTIVADOS NUMBER DEFAULT 0 NOT NULL,
  TOTAL_EMAIL_ACTUALIZADOS NUMBER DEFAULT 0 NOT NULL,
  TOTAL_EMAIL_INSERTADOS NUMBER DEFAULT 0 NOT NULL,
  TOTAL_SIN_CAMBIOS NUMBER DEFAULT 0 NOT NULL,
  TOTAL_OBSERVADOS NUMBER DEFAULT 0 NOT NULL,
  TOTAL_ERRORES NUMBER DEFAULT 0 NOT NULL,
  MENSAJE VARCHAR2(1000)
);
