-- Tabla de auditoría funcional por usuario/proceso
CREATE TABLE MAXIMO.SYNC_AD_MAXIMO_AUDIT (
  ID NUMBER PRIMARY KEY,
  RUN_ID NUMBER,
  FECHA_EVENTO TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  MODO VARCHAR2(20),
  PROCESO VARCHAR2(50),
  CEDULA VARCHAR2(20),
  PERSONID_MAXIMO_ANTERIOR VARCHAR2(100),
  PERSONID_MAXIMO_NUEVO VARCHAR2(100),
  PERSONID_AD VARCHAR2(100),
  EMAIL_ANTERIOR VARCHAR2(250),
  EMAIL_NUEVO VARCHAR2(250),
  EMAIL_AD VARCHAR2(250),
  ESTADO VARCHAR2(80) NOT NULL,
  MENSAJE VARCHAR2(1000),
  DETALLE_ERROR CLOB,
  CONSTRAINT FK_SYNC_AD_MAXIMO_AUDIT_RUN
    FOREIGN KEY (RUN_ID)
    REFERENCES MAXIMO.SYNC_AD_MAXIMO_RUN (RUN_ID)
);
