-- Tabla de auditoría de accesos y ejecuciones manuales
CREATE TABLE MAXIMO.SYNC_AD_MAXIMO_ACCESS_AUDIT (
  ID NUMBER PRIMARY KEY,
  FECHA_EVENTO TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  USUARIO VARCHAR2(100),
  IP_ORIGEN VARCHAR2(100),
  ACCION VARCHAR2(100),
  ESTADO VARCHAR2(100) NOT NULL,
  MENSAJE VARCHAR2(1000)
);
