-- Tabla de auditoría de correos de reporte
CREATE TABLE MAXIMO.SYNC_AD_MAXIMO_MAIL_AUDIT (
  ID NUMBER PRIMARY KEY,
  RUN_ID NUMBER,
  FECHA_ENVIO TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  DESTINATARIOS VARCHAR2(1000),
  COPIAS VARCHAR2(1000),
  ASUNTO VARCHAR2(500),
  ESTADO VARCHAR2(100) NOT NULL,
  MENSAJE VARCHAR2(1000),
  DETALLE_ERROR CLOB,
  CONSTRAINT FK_SYNC_AD_MAXIMO_MAIL_AUDIT_RUN
    FOREIGN KEY (RUN_ID)
    REFERENCES MAXIMO.SYNC_AD_MAXIMO_RUN (RUN_ID)
);
