-- Secuencias configurables para el modelo de persistencia Oracle
CREATE SEQUENCE MAXIMO.SYNC_AD_MAXIMO_RUN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MAXIMO.SYNC_AD_MAXIMO_AUDIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MAXIMO.SYNC_AD_MAXIMO_ACCESS_AUDIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MAXIMO.SYNC_AD_MAXIMO_MAIL_AUDIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencias sugeridas para MAXIMO.EMAIL cuando se necesite insertar correos.
-- Ajustar estos nombres en la configuración externa si la instancia usa secuencias distintas.
CREATE SEQUENCE MAXIMO.EMAILID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MAXIMO.ROWSTAMP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
