-- Índices básicos para consultas de trazabilidad y reportes
CREATE INDEX MAXIMO.IDX_SYNC_RUN_FECHA
  ON MAXIMO.SYNC_AD_MAXIMO_RUN (FECHA_INICIO);

CREATE INDEX MAXIMO.IDX_SYNC_RUN_ESTADO
  ON MAXIMO.SYNC_AD_MAXIMO_RUN (ESTADO);

CREATE INDEX MAXIMO.IDX_SYNC_AUDIT_RUN
  ON MAXIMO.SYNC_AD_MAXIMO_AUDIT (RUN_ID);

CREATE INDEX MAXIMO.IDX_SYNC_AUDIT_CEDULA
  ON MAXIMO.SYNC_AD_MAXIMO_AUDIT (CEDULA);

CREATE INDEX MAXIMO.IDX_SYNC_AUDIT_PERSONID_AD
  ON MAXIMO.SYNC_AD_MAXIMO_AUDIT (PERSONID_AD);

CREATE INDEX MAXIMO.IDX_SYNC_AUDIT_ESTADO
  ON MAXIMO.SYNC_AD_MAXIMO_AUDIT (ESTADO);

CREATE INDEX MAXIMO.IDX_SYNC_ACCESS_FECHA
  ON MAXIMO.SYNC_AD_MAXIMO_ACCESS_AUDIT (FECHA_EVENTO);

CREATE INDEX MAXIMO.IDX_SYNC_ACCESS_USUARIO
  ON MAXIMO.SYNC_AD_MAXIMO_ACCESS_AUDIT (USUARIO);

CREATE INDEX MAXIMO.IDX_SYNC_MAIL_RUN
  ON MAXIMO.SYNC_AD_MAXIMO_MAIL_AUDIT (RUN_ID);

CREATE INDEX MAXIMO.IDX_SYNC_MAIL_FECHA
  ON MAXIMO.SYNC_AD_MAXIMO_MAIL_AUDIT (FECHA_ENVIO);

CREATE INDEX MAXIMO.IDX_SYNC_MAIL_ESTADO
  ON MAXIMO.SYNC_AD_MAXIMO_MAIL_AUDIT (ESTADO);
