-- Secuencias de auditoría para sync_ad_maximo

CREATE SEQUENCE MAXIMO.SYNC_AD_MAXIMO_RUN_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MAXIMO.SYNC_AD_MAXIMO_AUDIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MAXIMO.SYNC_AD_MAXIMO_ACCESS_AUDIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MAXIMO.SYNC_AD_MAXIMO_MAIL_AUDIT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencias sugeridas para MAXIMO.EMAIL.
CREATE SEQUENCE MAXIMO.EMAILID_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MAXIMO.ROWSTAMP_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

