-- Tablas de auditoría y ejecución para sync_ad_maximo

CREATE TABLE MAXIMO.SYNC_AD_MAXIMO_RUN (
  RUN_ID NUMBER PRIMARY KEY,
  FECHA_INICIO TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  FECHA_FIN TIMESTAMP(6),
  MODO VARCHAR2(20) NOT NULL,
  PROCESO VARCHAR2(50) NOT NULL,
  USUARIO_EJECUTOR VARCHAR2(100),
  ORIGEN_EJECUCION VARCHAR2(30),
  ESTADO VARCHAR2(50) NOT NULL,
  TOTAL_MAXIMO NUMBER DEFAULT 0 NOT NULL,
  TOTAL_AD NUMBER DEFAULT 0 NOT NULL,
  TOTAL_MIGRADOS NUMBER DEFAULT 0 NOT NULL,
  TOTAL_CREADOS NUMBER DEFAULT 0 NOT NULL,
  TOTAL_INACTIVADOS NUMBER DEFAULT 0 NOT NULL,
  TOTAL_EMAIL_ACTUALIZADOS NUMBER DEFAULT 0 NOT NULL,
  TOTAL_EMAIL_INSERTADOS NUMBER DEFAULT 0 NOT NULL,
  TOTAL_SIN_CAMBIOS NUMBER DEFAULT 0 NOT NULL,
  TOTAL_OBSERVADOS NUMBER DEFAULT 0 NOT NULL,
  TOTAL_ERRORES NUMBER DEFAULT 0 NOT NULL,
  MENSAJE VARCHAR2(1000)
);

CREATE TABLE MAXIMO.SYNC_AD_MAXIMO_AUDIT (
  ID NUMBER PRIMARY KEY,
  RUN_ID NUMBER,
  FECHA_EVENTO TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  MODO VARCHAR2(20),
  PROCESO VARCHAR2(50),
  CEDULA VARCHAR2(20),
  PERSONID_MAXIMO_ANTERIOR VARCHAR2(100),
  PERSONID_MAXIMO_NUEVO VARCHAR2(100),
  PERSONID_AD VARCHAR2(100),
  EMAIL_ANTERIOR VARCHAR2(250),
  EMAIL_NUEVO VARCHAR2(250),
  EMAIL_AD VARCHAR2(250),
  ESTADO VARCHAR2(80) NOT NULL,
  MENSAJE VARCHAR2(1000),
  DETALLE_ERROR CLOB,
  CONSTRAINT FK_SYNC_AD_MAXIMO_AUDIT_RUN
    FOREIGN KEY (RUN_ID)
    REFERENCES MAXIMO.SYNC_AD_MAXIMO_RUN (RUN_ID)
);

CREATE TABLE MAXIMO.SYNC_AD_MAXIMO_ACCESS_AUDIT (
  ID NUMBER PRIMARY KEY,
  FECHA_EVENTO TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  USUARIO VARCHAR2(100),
  IP_ORIGEN VARCHAR2(100),
  ACCION VARCHAR2(100),
  ESTADO VARCHAR2(100) NOT NULL,
  MENSAJE VARCHAR2(1000)
);

CREATE TABLE MAXIMO.SYNC_AD_MAXIMO_MAIL_AUDIT (
  ID NUMBER PRIMARY KEY,
  RUN_ID NUMBER,
  FECHA_ENVIO TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  DESTINATARIOS VARCHAR2(1000),
  COPIAS VARCHAR2(1000),
  ASUNTO VARCHAR2(500),
  ESTADO VARCHAR2(100) NOT NULL,
  MENSAJE VARCHAR2(1000),
  DETALLE_ERROR CLOB,
  CONSTRAINT FK_SYNC_AD_MAXIMO_MAIL_AUDIT_RUN
    FOREIGN KEY (RUN_ID)
    REFERENCES MAXIMO.SYNC_AD_MAXIMO_RUN (RUN_ID)
);

